services:

  eeze_db:
      image: 'postgres:17.4-alpine3.21'
      container_name: eeze_db
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - eeze_postgres_data:/var/lib/postgresql/data
      networks:
        - eeze_network

  eeze_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eeze_backend
    depends_on:
      - eeze_db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - codecool.app.jwtSecret=${JWT_SECRET}
      - codecool.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
    networks:
      - eeze_network
  eeze_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eeze_frontend
    ports:  
    - "3000:80"
    depends_on:
      - eeze_backend
    networks:
      - eeze_network
    
volumes:
  eeze_postgres_data:

networks:
  eeze_network:
