services:

  db:
      image: 'postgres:17.4-alpine3.21'
      container_name: db
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - spendeeze_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - codecool.app.jwtSecret=${JWT_SECRET}
      - codecool.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
    networks:
      - spendeeze_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:  
    - "3000:80"
    depends_on:
      - backend
    networks:
      - spendeeze_network
    
volumes:
  postgres_data:

networks:
  spendeeze_network:
