version: '1'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:  
    - "3000:80"
    depends_on:
      - backend
    networks:
      - spendeeze_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
    - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - codecool.app.jwtSecret=${JWT_SECRET}
      - codecool.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
    networks:
      - spendeeze_network
    
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=spendeeze
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spendeeze_network

volumes:
  postgres_data:

networks:
  spendeeze_network:
